# vim: ft=yaml.ansible : ts=2 : sts=2 : sw=2 : et :
---

- name: Restart FRR on routers
  hosts: routers

  tasks:
    - name: Reload FRR
      ansible.builtin.command: "/usr/lib/frr/frr-reload"
      changed_when: false
