# vim: ft=yaml.ansible : ts=2 : sts=2 : sw=2 : et :
---

- name: Test HTTP
  hosts: webclient-servers
  gather_facts: false
  become: false

  tasks:
    - name: Check HTTP working
      ansible.builtin.command:
        argv:
          - "curl"
          - -s
          - "http://test-webdomain.example.com"
      changed_when: false
      register: curl_output

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ curl_output.stdout }}"
