# vim: ft=yaml.docker-compose : ts=2 : sts=2 : sw=2 : et :

x-ansible-pubkey: &ansible-pubkey
  volumes:
    - "$PWD/atsbox/keys/ansible-tower_mgmt.pub:/root/.ssh/authorized_keys:600"

services:
  router:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    image: frrbox
    privileged: false
    expose:
      - "179"
      - "22"
    <<: *ansible-pubkey

  server:
    image: srvbox
    expose:
      - "22"
    <<: *ansible-pubkey
