# vim: ts=2 : sts=2 : sw=2 : et :
---
version: '3'

services:
  r01_gw_side-a_corp:
    container_name: r01_gw_side-a_corp
    hostname: r01.gw.side-a.corp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "corp", "corp-sideA", "as65001" ]
    networks:
      - net_corp_xconn_a01
      - net_mgmt
      - net_corp_local_a01
      - net_corp_trans_a01

  r02_gw_side-a_corp:
    container_name: r02_gw_side-a_corp
    hostname: r02.gw.side-a.corp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "corp", "corp-sideA", "as65001" ]
    networks:
      - net_corp_xconn_a01
      - net_mgmt
      - net_corp_local_a02
      - net_corp_trans_a02

  r01_gw_side-b_corp:
    container_name: r01_gw_side-b_corp
    hostname: r01.gw.side-b.corp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "corp", "corp-sideB", "as65001" ]
    networks:
      - net_mgmt
      - net_corp_local_b01
      - net_corp_xconn_b01
      - net_corp_trans_b01

  r02_gw_side-b_corp:
    container_name: r02_gw_side-b_corp
    hostname: r02.gw.side-b.corp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "corp", "corp-sideB", "as65001" ]
    networks:
      - net_mgmt
      - net_corp_local_b02
      - net_corp_xconn_b01
      - net_corp_trans_b02

  r01_border_transit-a_isp:
    container_name: r01_border_transit-a_isp
    hostname: r01.border.transit-a.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transA", "as100" ]
    networks:
      - net_mgmt
      - net_corp_trans_a01
      - net_corp_trans_a02
      - net_trans_a01
      - net_trans_a02
      - net_trans_a03

  r02_border_transit-a_isp:
    container_name: r02_border_transit-a_isp
    hostname: r02.border.transit-a.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transA", "as100" ]
    networks:
      - net_mgmt
      - net_cloud_trans_a01
      - net_cloud_trans_a02
      - net_trans_a01
      - net_trans_a04
      - net_trans_a05

  r01_rr_transit-a_isp:
    container_name: r01_rr_transit-a_isp
    hostname: r01.rr.transit-a.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transA", "as100" ]
    networks:
      - net_mgmt
      - net_trans_a02
      - net_trans_a04
      - net_trans_a06

  r01_nni_transit-a_isp:
    container_name: r01_nni_transit-a_isp
    hostname: r01.nni.transit-a.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transA", "as100" ]
    networks:
      - net_mgmt
      - net_trans_a_b_nni01
      - net_trans_a03
      - net_trans_a05
      - net_trans_a06

  r01_border_transit-b_isp:
    container_name: r01_border_transit-b_isp
    hostname: r01.border.transit-b.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transB", "as200" ]
    networks:
      - net_mgmt
      - net_corp_trans_b01
      - net_corp_trans_b02
      - net_trans_b01
      - net_trans_b02
      - net_trans_b03

  r02_border_transit-b_isp:
    container_name: r02_border_transit-b_isp
    hostname: r02.border.transit-b.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transB", "as200" ]
    networks:
      - net_mgmt
      - net_cloud_trans_b01
      - net_cloud_trans_b02
      - net_trans_b01
      - net_trans_b04
      - net_trans_b05

  r01_rr_transit-b_isp:
    container_name: r01_rr_transit-b_isp
    hostname: r01.rr.transit-b.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transB", "as200" ]
    networks:
      - net_mgmt
      - net_trans_a02
      - net_trans_a04
      - net_trans_a06

  r01_nni_transit-b_isp:
    container_name: r01_nni_transit-b_isp
    hostname: r01.nni.transit-b.isp
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "transB", "as200" ]
    networks:
      - net_mgmt
      - net_trans_a_b_nni01
      - net_trans_b03
      - net_trans_b05
      - net_trans_b06

  r01_tor_cloud_web:
    container_name: r01_tor_cloud_web
    hostname: r01.tor.cloud.web
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "cloud", "as65010" ]
    networks:
      - net_mgmt
      - net_cloud_tor01
      - net_cloud_tor02
      - net_cloud_local01

  r01_border_cloud_web:
    container_name: r01_border_cloud_web
    hostname: r01.border.cloud.web
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "cloud", "as65010" ]
    networks:
      - net_mgmt
      - net_cloud_trans_a01
      - net_cloud_trans_b01
      - net_cloud_tor01

  r02_border_cloud_web:
    container_name: r02_border_cloud_web
    hostname: r02.border.cloud.web
    extends:
      file: base.yml
      service: router
    profiles: [ "topo", "cloud", "as65010" ]
    networks:
      - net_mgmt
      - net_cloud_trans_a02
      - net_cloud_trans_b02
      - net_cloud_tor02

  vpnuser01_corp:
    container_name: vpnuser01_corp
    hostname: vpnuser01.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideA", "as65001" ]
    networks:
      - net_mgmt
      - net_corp_local_a01

  vpnuser02_corp:
    container_name: vpnuser02_corp
    hostname: vpnuser02.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideA", "as65001" ]
    networks:
      - net_mgmt
      - net_corp_local_a01

  vpnuser03_corp:
    container_name: vpnuser03_corp
    hostname: vpnuser03.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideB", "as65002" ]
    networks:
      - net_mgmt
      - net_corp_local_b01

  vpnuser04_corp:
    container_name: vpnuser04_corp
    hostname: vpnuser04.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideB", "as65002" ]
    networks:
      - net_mgmt
      - net_corp_local_b01

  webclient01_corp:
    container_name: webclient01_corp
    hostname: webclient01.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideA", "as65001" ]
    networks:
      - net_mgmt
      - net_corp_local_a02

  webclient02_corp:
    container_name: webclient02_corp
    hostname: webclient02.corp
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "corp", "corp-sideB", "as65002" ]
    networks:
      - net_mgmt
      - net_corp_local_b02

  server01_cloud_web:
    container_name: server01_cloud_web
    hostname: server01.cloud.web
    extends:
      file: base.yml
      service: server
    profiles: [ "topo", "cloud", "as65010" ]
    expose:
      - "8080"
    networks:
      - net_mgmt
      - net_cloud_local01

  ansible-tower_mgmt:
    container_name: ansible-tower_mgmt
    hostname: ansible-tower.mgmt
    image: atsbox
    expose:
      - "22"
    volumes:
      - "$PWD/_ansible:/srv/ansible:rw"
      - "$PWD/atsbox/keys:/root/.ssh:rw"
    profiles: [ "topo", "cloud", "corp", "corp-sideA", "corp-sideB", "transA", \
                "transB", "as100", "as200", "as65001", "as65002", "as65010" ]
    networks:
      - default
      - net_mgmt

networks:
  net_mgmt:
    internal: true
    ipam:
      config:
        - subnet: 10.255.0.0/27

  net_corp_vpn:
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/24

  net_corp_local_a01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.1.0/24

  net_corp_local_a02:
    internal: true
    ipam:
      config:
        - subnet: 193.168.2.0/24

  net_corp_local_b01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.3.0/24

  net_corp_local_b02:
    internal: true
    ipam:
      config:
        - subnet: 193.168.4.0/24

  net_corp_xconn_a01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.100.0/29

  net_corp_xconn_b01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.200.0/29

  net_corp_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.10.101.0/29

  net_corp_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.10.102.0/29

  net_corp_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.10.201.0/29

  net_corp_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.10.202.0/29

  net_trans_a_b_nni01:
    internal: true
    ipam:
      config:
        - subnet: 11.11.0.0/29

  net_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.0.12.0/29

  net_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.0.13.0/29

  net_trans_a03:
    internal: true
    ipam:
      config:
        - subnet: 72.0.14.0/29

  net_trans_a04:
    internal: true
    ipam:
      config:
        - subnet: 72.0.23.0/29

  net_trans_a05:
    internal: true
    ipam:
      config:
        - subnet: 72.0.24.0/29

  net_trans_a06:
    internal: true
    ipam:
      config:
        - subnet: 72.0.34.0/29

  net_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.0.12.0/29

  net_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.0.13.0/29

  net_trans_b03:
    internal: true
    ipam:
      config:
        - subnet: 27.0.14.0/29

  net_trans_b04:
    internal: true
    ipam:
      config:
        - subnet: 27.0.23.0/29

  net_trans_b05:
    internal: true
    ipam:
      config:
        - subnet: 27.0.24.0/29

  net_trans_b06:
    internal: true
    ipam:
      config:
        - subnet: 27.0.34.0/29

  net_cloud_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.20.100.0/29

  net_cloud_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.20.200.0/29

  net_cloud_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.20.100.0/29

  net_cloud_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.20.200.0/29

  net_cloud_tor01:
    internal: true
    ipam:
      config:
        - subnet: 173.20.1.0/29

  net_cloud_tor02:
    internal: true
    ipam:
      config:
        - subnet: 173.20.2.0/29

  net_cloud_local01:
    internal: true
    ipam:
      config:
        - subnet: 173.30.0.0/24

