# vim: ft=docker-compose : ts=2 : sts=2 : sw=2 : et :
---
version: '3.8'
name: l3vpn-c-topology-networks-override

services:
  r01_gw_side-a_corp:
    networks:
      net_corp_xconn_a01:
        ipv4_address: 193.168.100.2
      net_corp_trans_a01:
        ipv4_address: 72.10.101.2

  r02_gw_side-a_corp:
    networks:
      net_corp_xconn_a01:
        ipv4_address: 193.168.100.3
      net_corp_trans_a02:
        ipv4_address: 72.10.102.2

  r01_gw_side-b_corp:
    networks:
      net_corp_xconn_b01:
        ipv4_address: 193.168.200.2
      net_corp_trans_b01:
        ipv4_address: 27.10.201.2

  r02_gw_side-b_corp:
    networks:
      net_corp_xconn_b01:
        ipv4_address: 193.168.200.3
      net_corp_trans_b02:
        ipv4_address: 27.10.202.2

  r01_border_transit-a_isp:
    networks:
      net_corp_trans_a01:
        ipv4_address: 72.10.101.3
      net_corp_trans_a02:
        ipv4_address: 72.10.102.3
      net_trans_a01:
        ipv4_address: 72.0.12.3
      net_trans_a04:
        ipv4_address: 72.0.23.2
      net_trans_a05:
        ipv4_address: 72.0.24.2

  r02_border_transit-a_isp:
    networks:
      net_cloud_trans_a01:
        ipv4_address: 72.20.100.3
      net_cloud_trans_a02:
        ipv4_address: 72.20.200.3
      net_trans_a02:
        ipv4_address: 72.0.13.3
      net_trans_a04:
        ipv4_address: 72.0.23.3
      net_trans_a06:
        ipv4_address: 72.0.34.2

  r01_rr_transit-a_isp:
    networks:
      net_trans_a01:
        ipv4_address: 72.0.12.2
      net_trans_a02:
        ipv4_address: 72.0.13.2
      net_trans_a03:
        ipv4_address: 72.0.13.2

  r01_nni_transit-a_isp:
    networks:
      net_trans_a_b_nni01:
        ipv4_address: 11.11.0.2
      net_trans_a03:
        ipv4_address: 72.0.14.3
      net_trans_a05:
        ipv4_address: 72.0.24.3
      net_trans_a06:
        ipv4_address: 72.0.34.3

  r01_border_transit-b_isp:
    networks:
      net_corp_trans_b01:
        ipv4_address: 27.10.201.3
      net_corp_trans_b02:
        ipv4_address: 27.10.202.3
      net_trans_b01:
        ipv4_address: 27.0.12.3
      net_trans_b04:
        ipv4_address: 27.0.23.2
      net_trans_b05:
        ipv4_address: 27.0.24.2

  r02_border_transit-b_isp:
    networks:
      net_cloud_trans_b01:
        ipv4_address: 27.20.100.3
      net_cloud_trans_b02:
        ipv4_address: 27.20.200.3
      net_trans_b02:
        ipv4_address: 27.0.12.3
      net_trans_b04:
        ipv4_address: 27.0.23.3
      net_trans_b06:
        ipv4_address: 27.0.24.2

  r01_rr_transit-b_isp:
    networks:
      net_trans_b01:
        ipv4_address: 27.0.12.2
      net_trans_b02:
        ipv4_address: 27.0.13.2
      net_trans_b03:
        ipv4_address: 27.0.14.2

  r01_nni_transit-b_isp:
    networks:
      net_trans_a_b_nni01:
        ipv4_address: 11.11.0.3
      net_trans_b03:
        ipv4_address: 27.0.14.3
      net_trans_b05:
        ipv4_address: 27.0.24.3
      net_trans_b06:
        ipv4_address: 27.0.34.3

  r01_tor_cloud_web:
    networks:
      net_cloud_tor01:
        ipv4_address: 173.20.1.2
      net_cloud_tor02:
        ipv4_address: 173.20.2.2

  r01_border_cloud_web:
    networks:
      net_cloud_trans_a01:
        ipv4_address: 72.20.100.2
      net_cloud_trans_b01:
        ipv4_address: 27.20.100.2
      net_cloud_tor01:
        ipv4_address: 173.20.1.3

  r02_border_cloud_web:
    networks:
      net_cloud_trans_a02:
        ipv4_address: 72.20.200.2
      net_cloud_trans_b02:
        ipv4_address: 27.20.200.2
      net_cloud_tor02:
        ipv4_address: 173.20.2.3

networks:
  net_corp_xconn_a01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.100.0/29
    driver_opts:
      com.docker.network.bridge.name: br-cxa01
      com.docker.network.container_iface_prefix: if-xcon

  net_corp_xconn_b01:
    internal: true
    ipam:
      config:
        - subnet: 193.168.200.0/29
    driver_opts:
      com.docker.network.bridge.name: br-cxb01
      com.docker.network.container_iface_prefix: if-xcon

  net_corp_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.10.101.0/29
    driver_opts:
      com.docker.network.bridge.name: br-cta01
      com.docker.network.container_iface_prefix: if-extl

  net_corp_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.10.102.0/29
    driver_opts:
      com.docker.network.bridge.name: br-cta02
      com.docker.network.container_iface_prefix: if-extl

  net_corp_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.10.201.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ctb01
      com.docker.network.container_iface_prefix: if-extl

  net_corp_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.10.202.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ctb02
      com.docker.network.container_iface_prefix: if-extl

  net_trans_a_b_nni01:
    internal: true
    ipam:
      config:
        - subnet: 11.11.0.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tabn01
      com.docker.network.container_iface_prefix: if-nni

  net_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.0.12.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta01
      com.docker.network.container_iface_prefix: if-intl

  net_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.0.13.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta02
      com.docker.network.container_iface_prefix: if-intl

  net_trans_a03:
    internal: true
    ipam:
      config:
        - subnet: 72.0.14.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta03
      com.docker.network.container_iface_prefix: if-intl

  net_trans_a04:
    internal: true
    ipam:
      config:
        - subnet: 72.0.23.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta04
      com.docker.network.container_iface_prefix: if-intl

  net_trans_a05:
    internal: true
    ipam:
      config:
        - subnet: 72.0.24.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta05
      com.docker.network.container_iface_prefix: if-intl

  net_trans_a06:
    internal: true
    ipam:
      config:
        - subnet: 72.0.34.0/29
    driver_opts:
      com.docker.network.bridge.name: br-ta06
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.0.12.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb01
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.0.13.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb02
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b03:
    internal: true
    ipam:
      config:
        - subnet: 27.0.14.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb03
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b04:
    internal: true
    ipam:
      config:
        - subnet: 27.0.23.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb04
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b05:
    internal: true
    ipam:
      config:
        - subnet: 27.0.24.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb05
      com.docker.network.container_iface_prefix: if-intl

  net_trans_b06:
    internal: true
    ipam:
      config:
        - subnet: 27.0.34.0/29
    driver_opts:
      com.docker.network.bridge.name: br-tb06
      com.docker.network.container_iface_prefix: if-intl

  net_cloud_trans_a01:
    internal: true
    ipam:
      config:
        - subnet: 72.20.100.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wta01
      com.docker.network.container_iface_prefix: if-extl

  net_cloud_trans_a02:
    internal: true
    ipam:
      config:
        - subnet: 72.20.200.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wta02
      com.docker.network.container_iface_prefix: if-extl

  net_cloud_trans_b01:
    internal: true
    ipam:
      config:
        - subnet: 27.20.100.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wtb01
      com.docker.network.container_iface_prefix: if-extl

  net_cloud_trans_b02:
    internal: true
    ipam:
      config:
        - subnet: 27.20.200.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wtb02
      com.docker.network.container_iface_prefix: if-extl

  net_cloud_tor01:
    internal: true
    ipam:
      config:
        - subnet: 173.20.1.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wi01
      com.docker.network.container_iface_prefix: if-intl

  net_cloud_tor02:
    internal: true
    ipam:
      config:
        - subnet: 173.20.2.0/29
    driver_opts:
      com.docker.network.bridge.name: br-wi02
      com.docker.network.container_iface_prefix: if-intl

